# Note: Until nvidia runtime [GPU] is supported with compose, please use the provided ./run.bash script instead (e.g. `./run.bash andrejorsula/drl_grasping:cuda_11.0.3 /bin/bash`)
# Issue to follow: https://github.com/docker/compose/issues/6691
version: "3.0"

services:
  drl_grasping:
    command: ros2 run drl_grasping train_enjoy.bash
    volumes:
      - /home/<user>/.ignition:/root/.ignition
      - /path/to/training:/root/drl_grasping/training
      - /path/to/pbr_textures:/root/drl_grasping/pbr_textures
    image: drl_grasping
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PARENT_IMAGE: nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04
        PYTHON3_VERSION: "3.8"
        ROS2_DISTRO: foxy
        IGNITION_VERSION: dome
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host

    # Neither of the following currently works, please see the note at the beginning of this file
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - capabilities: [gpu]
